[
  'Community',
  'Animal Shelter',
  'Assisted Living Services',
  'Facilities and Nursing Homes',
  'Caretakers',
  'Cemetery',
  'Courts',
  'Day Care and Preschools',
  'Disabled Persons Services',
  'Drug and Alcohol Services',
  'Education',
  'Vocational Schools',
  'Tutoring and Educational Services',
  'Primary and Secondary Schools',
  'Fraternities and Sororities',
  'Driving Schools',
  'Dance Schools',
  'Culinary Lessons and Schools',
  'Computer Training',
  'Colleges and Universities',
  'Art School',
  'Adult Education',
  'Government Departments and Agencies',
  'Government Lobbyists',
  'Housing Assistance and Shelters',
  'Law Enforcement',
  'Police Stations',
  'Fire Stations',
  'Correctional Institutions',
  'Libraries',
  'Military',
  'Organizations and Associations',
  'Youth Organizations',
  'Environmental',
  'Charities and Non-Profits',
  'Post Offices',
  'Public and Social Services',
  'Religious',
  'Temple',
  'Synagogues',
  'Mosques',
  'Churches',
  'Senior Citizen Services',
  'Retirement',
  'Food and Drink',
  'Bar',
  'Wine Bar',
  'Sports Bar',
  'Hotel Lounge',
  'Breweries',
  'Internet Cafes',
  'Nightlife',
  'Strip Club',
  'Night Clubs',
  'Karaoke',
  'Jazz and Blues Cafe',
  'Hookah Lounges',
  'Adult Entertainment',
  'Restaurants',
  'Winery',
  'Vegan and Vegetarian',
  'Turkish',
  'Thai',
  'Swiss',
  'Sushi',
  'Steakhouses',
  'Spanish',
  'Seafood',
  'Scandinavian',
  'Portuguese',
  'Pizza',
  'Moroccan',
  'Middle Eastern',
  'Mexican',
  'Mediterranean',
  'Latin American',
  'Korean',
  'Juice Bar',
  'Japanese',
  'Italian',
  'Indonesian',
  'Indian',
  'Ice Cream',
  'Greek',
  'German',
  'Gastropub',
  'French',
  'Food Truck',
  'Fish and Chips',
  'Filipino',
  'Fast Food',
  'Falafel',
  'Ethiopian',
  'Eastern European',
  'Donuts',
  'Distillery',
  'Diners',
  'Dessert',
  'Delis',
  'Cupcake Shop',
  'Cuban',
  'Coffee Shop',
  'Chinese',
  'Caribbean',
  'Cajun',
  'Cafe',
  'Burrito',
  'Burgers',
  'Breakfast Spot',
  'Brazilian',
  'Barbecue',
  'Bakery',
  'Bagel Shop',
  'Australian',
  'Asian',
  'American',
  'African',
  'Afghan',
  'Healthcare',
  'Healthcare Services',
  'Psychologists',
  'Pregnancy and Sexual Health',
  'Podiatrists',
  'Physical Therapy',
  'Optometrists',
  'Nutritionists',
  'Nurses',
  'Mental Health',
  'Medical Supplies and Labs',
  'Hospitals, Clinics and Medical Centers',
  'Emergency Services',
  'Dentists',
  'Counseling and Therapy',
  'Chiropractors',
  'Blood Banks and Centers',
  'Alternative Medicine',
  'Acupuncture',
  'Physicians',
  'Urologists',
  'Respiratory',
  'Radiologists',
  'Psychiatrists',
  'Plastic Surgeons',
  'Pediatricians',
  'Pathologists',
  'Orthopedic Surgeons',
  'Ophthalmologists',
  'Oncologists',
  'Obstetricians and Gynecologists',
  'Neurologists',
  'Internal Medicine',
  'General Surgery',
  'Gastroenterologists',
  'Family Medicine',
  'Ear, Nose and Throat',
  'Dermatologists',
  'Cardiologists',
  'Anesthesiologists',
  'Interest',
  'Interest Earned',
  'Interest Charged',
  'Payment',
  'Credit Card',
  'Rent',
  'Loan',
  'Recreation',
  'Arts and Entertainment',
  'Theatrical Productions',
  'Symphony and Opera',
  'Sports Venues',
  'Social Clubs',
  'Psychics and Astrologers',
  'Party Centers',
  'Music and Show Venues',
  'Museums',
  'Movie Theatres',
  'Fairgrounds and Rodeos',
  'Entertainment',
  'Dance Halls and Saloons',
  'Circuses and Carnivals',
  'Casinos and Gaming',
  'Bowling',
  'Billiards and Pool',
  'Art Dealers and Galleries',
  'Arcades and Amusement Parks',
  'Aquarium',
  'Athletic Fields',
  'Baseball',
  'Basketball',
  'Batting Cages',
  'Boating',
  'Campgrounds and RV Parks',
  'Canoes and Kayaks',
  'Combat Sports',
  'Cycling',
  'Dance',
  'Equestrian',
  'Football',
  'Go Carts',
  'Golf',
  'Gun Ranges',
  'Gymnastics',
  'Gyms and Fitness Centers',
  'Hiking',
  'Hockey',
  'Hot Air Balloons',
  'Hunting and Fishing',
  'Landmarks',
  'Monuments and Memorials',
  'Historic Sites',
  'Gardens',
  'Buildings and Structures',
  'Miniature Golf',
  'Outdoors',
  'Rivers',
  'Mountains',
  'Lakes',
  'Forests',
  'Beaches',
  'Paintball',
  'Parks',
  'Playgrounds',
  'Picnic Areas',
  'Natural Parks',
  'Personal Trainers',
  'Race Tracks',
  'Racquet Sports',
  'Racquetball',
  'Rafting',
  'Recreation Centers',
  'Rock Climbing',
  'Running',
  'Scuba Diving',
  'Skating',
  'Skydiving',
  'Snow Sports',
  'Soccer',
  'Sports and Recreation Camps',
  'Sports Clubs',
  'Stadiums and Arenas',
  'Swimming',
  'Tennis',
  'Water Sports',
  'Yoga and Pilates',
  'Zoo',
  'Service',
  'Advertising and Marketing',
  'Writing, Copywriting and Technical Writing',
  'Search Engine Marketing and Optimization',
  'Public Relations',
  'Promotional Items',
  'Print, TV, Radio and Outdoor Advertising',
  'Online Advertising',
  'Market Research and Consulting',
  'Direct Mail and Email Marketing Services',
  'Creative Services',
  'Advertising Agencies and Media Buyers',
  'Art Restoration',
  'Audiovisual',
  'Automation and Control Systems',
  'Automotive',
  'Towing',
  'Motorcycle, Moped and Scooter Repair',
  'Maintenance and Repair',
  'Car Wash and Detail',
  'Car Appraisers',
  'Auto Transmission',
  'Auto Tires',
  'Auto Smog Check',
  'Auto Oil and Lube',
  'Business and Strategy Consulting',
  'Business Services',
  'Printing and Publishing',
  'Cable',
  'Chemicals and Gasses',
  'Cleaning',
  'Computers',
  'Software Development',
  'Construction',
  'Specialty',
  'Roofers',
  'Painting',
  'Masonry',
  'Infrastructure',
  'Heating, Ventilating and Air Conditioning',
  'Electricians',
  'Contractors',
  'Carpet and Flooring',
  'Carpenters',
  'Credit Counseling and Bankruptcy Services',
  'Dating and Escort',
  'Employment Agencies',
  'Engineering',
  'Media',
  'Events and Event Planning',
  'Financial',
  'Taxes',
  'Student Aid and Grants',
  'Stock Brokers',
  'Loans and Mortgages',
  'Holding and Investment Offices',
  'Fund Raising',
  'Financial Planning and Investments',
  'Credit Reporting',
  'Collections',
  'Check Cashing',
  'Business Brokers and Franchises',
  'Banking and Finance',
  'ATMs',
  'Accounting and Bookkeeping',
  'Food and Beverage',
  'Distribution',
  'Catering',
  'Funeral Services',
  'Geological',
  'Home Improvement',
  'Upholstery',
  'Tree Service',
  'Swimming Pool Maintenance and Services',
  'Storage',
  'Pools and Spas',
  'Plumbing',
  'Pest Control',
  'Movers',
  'Mobile Homes',
  'Lighting Fixtures',
  'Landscaping and Gardeners',
  'Kitchens',
  'Interior Design',
  'Housewares',
  'Home Inspection Services',
  'Home Appliances',
  'Heating, Ventilation and Air Conditioning',
  'Hardware and Services',
  'Fences, Fireplaces and Garage Doors',
  'Doors and Windows',
  'Architects',
  'Household',
  'Human Resources',
  'Immigration',
  'Import and Export',
  'Industrial Machinery and Vehicles',
  'Insurance',
  'Internet Services',
  'Leather',
  'Legal',
  'Logging and Sawmills',
  'Machine Shops',
  'Management',
  'Manufacturing',
  'Apparel and Fabric Products',
  'Computers and Office Machines',
  'Electrical Equipment and Components',
  'Furniture and Fixtures',
  'Glass Products',
  'Industrial Machinery and Equipment',
  'Leather Goods',
  'Metal Products',
  'Nonmetallic Mineral Products',
  'Paper Products',
  'Petroleum',
  'Plastic Products',
  'Rubber Products',
  'Service Instruments',
  'Textiles',
  'Tobacco',
  'Transportation Equipment',
  'Wood Products',
  'Media Production',
  'Metals',
  'Mining',
  'Coal',
  'Metal',
  'Non-Metallic Minerals',
  'News Reporting',
  'Oil and Gas',
  'Packaging',
  'Paper',
  'Personal Care',
  'Tattooing',
  'Tanning Salons',
  'Spas',
  'Skin Care',
  'Piercing',
  'Massage Clinics and Therapists',
  'Manicures and Pedicures',
  'Laundry and Garment Services',
  'Hair Salons and Barbers',
  'Hair Removal',
  'Photography',
  'Plastics',
  'Rail',
  'Real Estate',
  'Real Estate Development and Title Companies',
  'Real Estate Appraiser',
  'Real Estate Agents',
  'Property Management',
  'Corporate Housing',
  'Commercial Real Estate',
  'Building and Land Surveyors',
  'Boarding Houses',
  'Apartments, Condos and Houses',
  'Refrigeration and Ice',
  'Renewable Energy',
  'Repair Services',
  'Research',
  'Rubber',
  'Scientific',
  'Security and Safety',
  'Shipping and Freight',
  'Subscription',
  'Tailors',
  'Telecommunication Services',
  'Tourist Information and Services',
  'Transportation',
  'Travel Agents and Tour Operators',
  'Utilities',
  'Water',
  'Sanitary and Waste Management',
  'Heating, Ventilating, and Air Conditioning',
  'Gas',
  'Electric',
  'Veterinarians',
  'Water and Waste Management',
  'Web Design and Development',
  'Welding',
  'Agriculture and Forestry',
  'Crop Production',
  'Forestry',
  'Livestock and Animals',
  'Services',
  'Art and Graphic Design',
  'Shops',
  'Adult',
  'Antiques',
  'Arts and Crafts',
  'Auctions',
  'Used Car Dealers',
  'Salvage Yards',
  'RVs and Motor Homes',
  'Motorcycles, Mopeds and Scooters',
  'Classic and Antique Car',
  'Car Parts and Accessories',
  'Car Dealers and Leasing',
  'Beauty Products',
  'Bicycles',
  'Boat Dealers',
  'Bookstores',
  'Cards and Stationery',
  'Children',
  'Clothing and Accessories',
  "Women's Store",
  'Swimwear',
  'Shoe Store',
  "Men's Store",
  'Lingerie Store',
  "Kids' Store",
  'Boutique',
  'Accessories Store',
  'Computers and Electronics',
  'Video Games',
  'Mobile Phones',
  'Cameras',
  'Construction Supplies',
  'Convenience Stores',
  'Costumes',
  'Dance and Music',
  'Department Stores',
  'Digital Purchase',
  'Discount Stores',
  'Electrical Equipment',
  'Equipment Rental',
  'Flea Markets',
  'Florists',
  'Food and Beverage Store',
  'Health Food',
  'Farmers Markets',
  'Beer, Wine and Spirits',
  'Fuel Dealer',
  'Furniture and Home Decor',
  'Gift and Novelty',
  'Glasses and Optometrist',
  'Hardware Store',
  'Hobby and Collectibles',
  'Industrial Supplies',
  'Jewelry and Watches',
  'Luggage',
  'Marine Supplies',
  'Music, Video and DVD',
  'Musical Instruments',
  'Newsstands',
  'Office Supplies',
  'Outlet',
  'Pawn Shops',
  'Pets',
  'Pharmacies',
  'Photos and Frames',
  'Shopping Centers and Malls',
  'Sporting Goods',
  'Supermarkets and Groceries',
  'Toys',
  'Vintage and Thrift',
  'Warehouses and Wholesale Stores',
  'Wedding and Bridal',
  'Wholesale',
  'Lawn and Garden',
  'Tax',
  'Refund',
  'Transfer',
  'Internal Account Transfer',
  'ACH',
  'Billpay',
  'Check',
  'Credit',
  'Debit',
  'Deposit',
  'ATM',
  'Keep the Change Savings Program',
  'Payroll',
  'Benefits',
  'Third Party',
  'Venmo',
  'Square Cash',
  'Square',
  'PayPal',
  'Dwolla',
  'Coinbase',
  'Chase QuickPay',
  'Acorns',
  'Digit',
  'Betterment',
  'Plaid',
  'Wire',
  'Withdrawal',
  'Save As You Go',
  'Travel',
  'Airlines and Aviation Services',
  'Airports',
  'Boat',
  'Bus Stations',
  'Car and Truck Rentals',
  'Car Service',
  'Ride Share',
  'Charter Buses',
  'Cruises',
  'Gas Stations',
  'Heliports',
  'Limos and Chauffeurs',
  'Lodging',
  'Resorts',
  'Lodges and Vacation Rentals',
  'Hotels and Motels',
  'Hostels',
  'Cottages and Cabins',
  'Bed and Breakfasts',
  'Parking',
  'Public Transportation Services',
  'Taxi',
  'Tolls and Fees',
  'Transportation Centers',
];

[
  'Community',
  'Assisted Living Services',
  'Education',
  'Law Enforcement',
  'Organizations and Associations',
  'Religious',
  'Food and Drink',
  'Bar',
  'Nightlife',
  'Restaurants',
  'Healthcare',
  'Healthcare Services',
  'Physicians',
  'Interest',
  'Payment',
  'Recreation',
  'Arts and Entertainment',
  'Entertainment',
  'Landmarks',
  'Outdoors',
  'Parks',
  'Service',
  'Advertising and Marketing',
  'Automotive',
  'Computers',
  'Construction',
  'Financial',
  'Food and Beverage',
  'Home Improvement',
  'Manufacturing',
  'Mining',
  'Personal Care',
  'Real Estate',
  'Utilities',
  'Agriculture and Forestry',
  'Shops',
  'Clothing and Accessories',
  'Computers and Electronics',
  'Food and Beverage Store',
  'Outlet',
  'Tax',
  'Transfer',
  'Check',
  'Deposit',
  'Third Party',
  'Withdrawal',
  'Travel',
  'Lodging',
];

COMMONE = [
  'Community',
  'Assisted Living Services',
  'Education',
  'Law Enforcement',
  'Organizations and Associations',
  'Religious',
  'Senior Citizen Services',
  'Food and Drink',
  'Bar',
  'Nightlife',
  'Restaurants',
  'Healthcare',
  'Healthcare Services',
  'Physicians',
  'Interest',
  'Payment',
  'Rent',
  'Recreation',
  'Arts and Entertainment',
  'Entertainment',
  'Landmarks',
  'Outdoors',
  'Parks',
  'Service',
  'Advertising and Marketing',
  'Automotive',
  'Maintenance and Repair',
  'Business Services',
  'Chemicals and Gasses',
  'Computers',
  'Software Development',
  'Construction',
  'Specialty',
  'Roofers',
  'Painting',
  'Electricians',
  'Contractors',
  'Carpet and Flooring',
  'Carpenters',
  'Financial',
  'Food and Beverage',
  'Home Improvement',
  'Storage',
  'Manufacturing',
  'Petroleum',
  'Textiles',
  'Tobacco',
  'Mining',
  'Personal Care',
  'Rail',
  'Real Estate',
  'Utilities',
  'Agriculture and Forestry',
  'Shops',
  'Clothing and Accessories',
  "Women's Store",
  'Swimwear',
  'Shoe Store',
  "Men's Store",
  'Lingerie Store',
  "Kids' Store",
  'Boutique',
  'Accessories Store',
  'Computers and Electronics',
  'Food and Beverage Store',
  'Outlet',
  'Tax',
  'Transfer',
  'Check',
  'Deposit',
  'ATM',
  'Payroll',
  'Third Party',
  'Withdrawal',
  'Travel',
  'Car Service',
  'Lodging',
];
